# Generated by Django 6.0.1 on 2026-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_avatar_url_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
