# Generated by Django 6.0.1 on 2026-01-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_type', models.CharField(choices=[('campaign', 'Campaign'), ('one_shot', 'One-shot')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('system', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['series_type', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('recap', models.TextField()),
                ('aired_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='games.gameseries')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('series', 'episode_number')},
            },
        ),
    ]
